/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as JoinRouteImport } from './routes/join'
import { Route as EventsRouteImport } from './routes/events'
import { Route as AdministrationsRouteImport } from './routes/administrations'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ResearchSlugRouteImport } from './routes/research_.$slug'
import { Route as EventsEventIdRouteImport } from './routes/events_.$eventId'
import { Route as AdminTeamRouteImport } from './routes/admin/team'
import { Route as AdminResearchRouteImport } from './routes/admin/research'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminLabsRouteImport } from './routes/admin/labs'
import { Route as AdminHomeRouteImport } from './routes/admin/home'
import { Route as AdminEventsRouteImport } from './routes/admin/events'
import { Route as AdminBoardTransitionRouteImport } from './routes/admin/board-transition'
import { Route as AdminAdminsRouteImport } from './routes/admin/admins'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationsRoute = AdministrationsRouteImport.update({
  id: '/administrations',
  path: '/administrations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ResearchSlugRoute = ResearchSlugRouteImport.update({
  id: '/research_/$slug',
  path: '/research/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events_/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResearchRoute = AdminResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLabsRoute = AdminLabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomeRoute = AdminHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBoardTransitionRoute = AdminBoardTransitionRouteImport.update({
  id: '/board-transition',
  path: '/board-transition',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/administrations': typeof AdministrationsRoute
  '/events': typeof EventsRoute
  '/join': typeof JoinRoute
  '/privacy': typeof PrivacyRoute
  '/research': typeof ResearchRoute
  '/team': typeof TeamRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/board-transition': typeof AdminBoardTransitionRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/labs': typeof AdminLabsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/research': typeof AdminResearchRoute
  '/admin/team': typeof AdminTeamRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/research/$slug': typeof ResearchSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/administrations': typeof AdministrationsRoute
  '/events': typeof EventsRoute
  '/join': typeof JoinRoute
  '/privacy': typeof PrivacyRoute
  '/research': typeof ResearchRoute
  '/team': typeof TeamRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/board-transition': typeof AdminBoardTransitionRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/labs': typeof AdminLabsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/research': typeof AdminResearchRoute
  '/admin/team': typeof AdminTeamRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/research/$slug': typeof ResearchSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/administrations': typeof AdministrationsRoute
  '/events': typeof EventsRoute
  '/join': typeof JoinRoute
  '/privacy': typeof PrivacyRoute
  '/research': typeof ResearchRoute
  '/team': typeof TeamRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/board-transition': typeof AdminBoardTransitionRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/labs': typeof AdminLabsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/research': typeof AdminResearchRoute
  '/admin/team': typeof AdminTeamRoute
  '/events_/$eventId': typeof EventsEventIdRoute
  '/research_/$slug': typeof ResearchSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/administrations'
    | '/events'
    | '/join'
    | '/privacy'
    | '/research'
    | '/team'
    | '/admin/admins'
    | '/admin/board-transition'
    | '/admin/events'
    | '/admin/home'
    | '/admin/labs'
    | '/admin/login'
    | '/admin/research'
    | '/admin/team'
    | '/events/$eventId'
    | '/research/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/administrations'
    | '/events'
    | '/join'
    | '/privacy'
    | '/research'
    | '/team'
    | '/admin/admins'
    | '/admin/board-transition'
    | '/admin/events'
    | '/admin/home'
    | '/admin/labs'
    | '/admin/login'
    | '/admin/research'
    | '/admin/team'
    | '/events/$eventId'
    | '/research/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/administrations'
    | '/events'
    | '/join'
    | '/privacy'
    | '/research'
    | '/team'
    | '/admin/admins'
    | '/admin/board-transition'
    | '/admin/events'
    | '/admin/home'
    | '/admin/labs'
    | '/admin/login'
    | '/admin/research'
    | '/admin/team'
    | '/events_/$eventId'
    | '/research_/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdministrationsRoute: typeof AdministrationsRoute
  EventsRoute: typeof EventsRoute
  JoinRoute: typeof JoinRoute
  PrivacyRoute: typeof PrivacyRoute
  ResearchRoute: typeof ResearchRoute
  TeamRoute: typeof TeamRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  ResearchSlugRoute: typeof ResearchSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administrations': {
      id: '/administrations'
      path: '/administrations'
      fullPath: '/administrations'
      preLoaderRoute: typeof AdministrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/research_/$slug': {
      id: '/research_/$slug'
      path: '/research/$slug'
      fullPath: '/research/$slug'
      preLoaderRoute: typeof ResearchSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events_/$eventId': {
      id: '/events_/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/research': {
      id: '/admin/research'
      path: '/research'
      fullPath: '/admin/research'
      preLoaderRoute: typeof AdminResearchRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/labs': {
      id: '/admin/labs'
      path: '/labs'
      fullPath: '/admin/labs'
      preLoaderRoute: typeof AdminLabsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/home': {
      id: '/admin/home'
      path: '/home'
      fullPath: '/admin/home'
      preLoaderRoute: typeof AdminHomeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/board-transition': {
      id: '/admin/board-transition'
      path: '/board-transition'
      fullPath: '/admin/board-transition'
      preLoaderRoute: typeof AdminBoardTransitionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminBoardTransitionRoute: typeof AdminBoardTransitionRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminHomeRoute: typeof AdminHomeRoute
  AdminLabsRoute: typeof AdminLabsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminResearchRoute: typeof AdminResearchRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminsRoute: AdminAdminsRoute,
  AdminBoardTransitionRoute: AdminBoardTransitionRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminHomeRoute: AdminHomeRoute,
  AdminLabsRoute: AdminLabsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminResearchRoute: AdminResearchRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdministrationsRoute: AdministrationsRoute,
  EventsRoute: EventsRoute,
  JoinRoute: JoinRoute,
  PrivacyRoute: PrivacyRoute,
  ResearchRoute: ResearchRoute,
  TeamRoute: TeamRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  ResearchSlugRoute: ResearchSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
